# Generated by Django 4.2.5 on 2023-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shareRes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_name2",
        ),
    ]
